apiVersion: v1
kind: ConfigMap
metadata:
  name: api-fastify-config
  namespace: api-fastify
data:
  NODE_ENV: "production"
  PORT: "3000"
  DEPORTBACK_URL: "http://35.224.94.116"
  INVENTARIO_U_URL: "http://158.247.121.202"
